language: go

go:
  - "1.13.x"
  - "1.14.x"
  - "1.15.x"
  - "master"

os:
  - linux

go_import_path: github.com/uhonliu/go-ratelimiter

env:
  - GO111MODULE=on

services:
  - redis

install: go mod tidy

script: go test -race  -v .
